# Déclaration des reseaux
networks:
  devops-net:
    driver: bridge

# volumes BD
volumes:
  mysqldb_data:   


services:
  # Service mysql
  mysql:
    image: mysql:latest
    container_name: 2b-mysql-container
    ports:
      - "3306:3306"
    restart: unless-stopped  
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      #      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysqldb_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - devops-net


