# PersistentVolume pour le stockage persistant de MySQL
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.database.pv.name }}

spec:
  capacity:
    storage: {{ .Values.database.pv.storage }}
  accessModes:
    - {{ .Values.database.pv.accessMode }}

  persistentVolumeReclaimPolicy: {{ .Values.database.pv.reclaimPolicy }}
  storageClassName: {{ .Values.database.pv.storageClass }}
  hostPath:
    path: {{ .Values.database.pv.hostPath }} 
    type: {{ .Values.database.pv.hostPathType }}

---
# PersistentVolumeClaim pour lier le stockage au déploiement
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.database.pvc.name }}
  namespace: {{ .Values.database.namespace }}

spec:
  accessModes:
  - {{ .Values.database.pvc.accessMode }}

  resources:
    requests:
      storage: {{ .Values.database.pvc.storage }}

  storageClassName: {{ .Values.database.pv.storageClass }}
  volumeName: {{ .Values.database.pv.name }}