# Secret pour les identifiants sensibles de database
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secret.name }}
  namespace: {{ .Values.database.namespace }}
type: Opaque
data:
  {{ .Values.database.secret.keys.database }}: {{ .Values.database.secret.data.database }}
  {{ .Values.database.secret.keys.user }}: {{ .Values.database.secret.data.user }}
  {{ .Values.database.secret.keys.password }}: {{ .Values.database.secret.data.password }}
  {{ .Values.database.secret.keys.rootPassword }}: {{ .Values.database.secret.data.rootPassword }}