# Secret pour les identifiants sensibles de database
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secret.name }}
  namespace: {{ .Values.database.namespace }}
type: Opaque
data:
  MYSQL_DATABASE: {{ .Values.database.secret.data.database }}
  MYSQL_USER: {{ .Values.database.secret.data.user }}
  MYSQL_PASSWORD: {{ .Values.database.secret.data.password }}
  MYSQL_ROOT_PASSWORD: {{ .Values.database.secret.data.rootPassword }}