# Secret pour les identifiants sensibles de l'application Spring Boot
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.springapp.secret.name }}
  namespace: {{ .Values.springapp.namespace }}
type: Opaque
data:
  {{ .Values.springapp.secret.keys.username }}: {{ .Values.springapp.secret.data.username }}
  {{ .Values.springapp.secret.keys.password }}: {{ .Values.springapp.secret.data.password }}