# Secret pour les identifiants sensibles de l'application Spring Boot
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.springapp.secret.name }}
  namespace: {{ .Values.springapp.namespace }}
type: Opaque
data:
  spring.datasource.username: {{ .Values.springapp.secret.data.username }}
  spring.datasource.password: {{ .Values.springapp.secret.data.password }}